#!/bin/bash

if [ -z "$1" ]
  then echo "Please provide the name of the game, e.g.  ./run_cpu breakout "; exit 0
fi
ENV=$1
FRAMEWORK="alewrap"
postfix="FINAL"
game_path=$PWD"/roms/"
env_params="useRGB=true"
agent="NeuralQLearner"
n_replay=1
netfile="\"DQN3_0_1_"$1"_"$postfix"_Y.t7\""
frame_dump_path="/home/ubuntu/tmp/"$1"/"
update_freq=4
actrep=4
discount=0.95
seed=1
learn_start=1
pool_frms_type="\"max\""
pool_frms_size=2
initial_priority="false"
replay_memory=1000000
eps_end=0
eps_endt=0
lr=0.00025
agent_type="DQN3_0_1"
preproc_net="\"net_downsample_2x_full_y\""
agent_name=$agent_type"_"$1"_"$postfix"_Y"
state_dim=7056
ncols=1
agent_params="lr="$lr",ep=1,ep_end="$eps_end",ep_endt="$eps_endt",discount="$discount",hist_len=4,learn_start="$learn_start",replay_memory="$replay_memory",update_freq="$update_freq",n_replay="$n_replay",network="$netfile",preproc="$preproc_net",state_dim="$state_dim",minibatch_size=32,rescale_r=1,ncols="$ncols",bufferSize=512,valid_size=500,target_q=10000,clip_delta=1,min_reward=-1,max_reward=1"
steps=50000000
eval_freq=1000000
eval_steps=1000000
prog_freq=1000000
save_freq=1000000
gpu=0
random_starts=30
pool_frms="type="$pool_frms_type",size="$pool_frms_size
num_threads=4

# set ALE_HOST env-var to play on remote, or skip to run localy
if [ ! -z "${ALE_HOST}" ] ; then
	[ -z "${ALE_PORT}" ] && ALE_PORT=1567
  host_port=" -ale_host ${ALE_HOST} -ale_port ${ALE_PORT} -ale_login ${ALE_LOGIN} -ale_pass ${ALE_PASS} "
fi

mkdir -p $frame_dump_path
args="-frame_dump_path $frame_dump_path -framework $FRAMEWORK -game_path $game_path -name $agent_name -env $ENV -env_params $env_params -agent $agent -agent_params $agent_params -steps $steps -eval_freq $eval_freq -eval_steps $eval_steps -prog_freq $prog_freq -save_freq $save_freq -actrep $actrep -gpu $gpu -random_starts $random_starts -pool_frms $pool_frms -seed $seed -threads $num_threads"
args="$args $host_port"
echo $args

cd dqn
#qlua play_agent.lua $args
/home/ubuntu/torch/install/bin/luajit play_agent.lua $args
