#!/bin/bash
env ALE_LOGIN=team_10 ALE_PASS=yzvpDK ALE_HOST=52.8.225.234 ALE_PORT=17010 ./play_gpu seaquest > log_seaquest.txt
sleep 100
env ALE_LOGIN=team_10 ALE_PASS=yzvpDK ALE_HOST=52.8.225.234 ALE_PORT=17010 ./play_gpu gopher > log_gother.txt
sleep 100
env ALE_LOGIN=team_10 ALE_PASS=yzvpDK ALE_HOST=52.8.225.234 ALE_PORT=17010 ./play_gpu tutankham > log_tutankham.txt
